<?php

$params = array_merge(
        require __DIR__ . '/../../common/config/params.php', require __DIR__ . '/../../common/config/params-local.php', require __DIR__ . '/params.php', require __DIR__ . '/params-local.php'
);

return [
    'id' => 'commodity',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'commodity\controllers',
    'bootstrap' => [
        'log',
        'authentication',
        'commodityManage',
        'commodityUnit',
        'commoditybatch',
        'ossImage',
        'classification',
        'service',
        'serviceaddition',
        'serviceclassification',
        'token',
        'depot',
        'store',
        'supplier',
        'employeetype',
        'employee',
        'employeeuser',
        'purchase',
        'picking',
        'pickingcommodity',
        'pickingdestroy',
        'damaged',
        'damagedcommodity',
        'damageddestroy',
        'inventory',
        'customerinfomation',
        'customercarstirebrand',
        'carbasicinformation',
        'authorization',
        'bill',
        'finance',
        'frontBridge',
        'import',
        'export',
        'member',
        'memberPoint'
    ],
    'modules' => [
        'authentication' => 'commodity\modules\authentication\Module',
        'commodityManage' => 'commodity\modules\commodityManage\Module',
        'commodityUnit' => 'commodity\modules\commodityUnit\Module',
        'commoditybatch' => 'commodity\modules\commoditybatch\Module',
        'classification' => 'commodity\modules\classification\Module',
        'ossImage' => 'commodity\modules\ossImage\Module',
        'service' => 'commodity\modules\service\Module',
        'serviceaddition' => 'commodity\modules\serviceaddition\Module',
        'serviceclassification' => 'commodity\modules\serviceclassification\Module',
        'employee' => 'commodity\modules\employee\Module',
        'employeetype' => 'commodity\modules\employeetype\Module',
        'supplier' => 'commodity\modules\supplier\Module',
        'depot' => 'commodity\modules\depot\Module',
        'store' => 'commodity\modules\store\Module',
        'employeeuser' => 'commodity\modules\employeeuser\Module',
        'employeeuser' => 'commodity\modules\employeeuser\Module',
        'purchase' => 'commodity\modules\purchase\Module',
        'picking' => 'commodity\modules\picking\Module',
        'pickingdestroy' => 'commodity\modules\pickingdestroy\Module',
        'pickingcommodity' => 'commodity\modules\pickingcommodity\Module',
        'damaged' => 'commodity\modules\damaged\Module',
        'damageddestroy' => 'commodity\modules\damageddestroy\Module',
        'damagedcommodity' => 'commodity\modules\damagedcommodity\Module',
        'inventory' => 'commodity\modules\inventory\Module',
        'customerinfomation' => 'commodity\modules\customerinfomation\Module',
        'customercarstirebrand' => 'commodity\modules\customercarstirebrand\Module',
        'carbasicinformation' => 'commodity\modules\carbasicinformation\Module',
        'authorization' => 'commodity\modules\authorization\Module',
        'bill' => 'commodity\modules\bill\Module',
        'finance' => 'commodity\modules\finance\Module',
        'frontBridge' => 'commodity\modules\frontBridge\Module',
        'import' => 'commodity\modules\import\Module',
        'export' => 'commodity\modules\export\Module',
        'member' => 'commodity\modules\member\Module',
        'memberPoint' => 'commodity\modules\memberPoint\Module',
    ],
    'components' => [
        'user' => [
            'identityClass' => 'commodity\components\tokenAuthentication\UserIdentity',
            'enableAutoLogin' => false,
            'enableSession' => false,
            'loginUrl' => '/'
        ],
        'session' => [
            // this is the name of the session cookie used for login on the backend
            'name' => 'commodity',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'index/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'suffix' => '.do',
            'rules' => [
                'captcha' => 'index/captcha',
                'error' => 'index/error',
                'api-hostname' => 'index/api-hostname',
                '' => 'index',
                '<controller:[a-z-]+>' => '<controller>',
                '<controller:[a-z-]+>/<action:[a-z-]+>' => '<controller>/<action>',
            ],
        ],
        'token' => [
            'class' => 'commodity\components\tokenAuthentication\AccessTokenAuthentication',
            'dbHandler' => 'commodity\models\common\UserModel',
            'tokenName' => 'token',
            'tokenTimeout' => '3600'
        ],
    ],
    'params' => $params,
];
